spring.application.name=forum-service-diplom-project
logging.level.root=debug

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/

openshare.resource.url=http://localhost:8082
openshare.tracker.url=http://localhost:8081

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:C:./database/test;AUTO_SERVER=TRUE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect