spring.application.name=forum-service-diplom-project
logging.level.root=info

spring.web.resources.static-locations=file:src/main/resources/static/

openshare.resource.url=http://localhost:8082
openshare.tracker.url=http://localhost:8081


spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:37770/postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect